spring:
  application:
    name: eurekaClient
    rabbitmq: #消息队列服务器
      host: localhost
      port: 5762
      username: guest
      password: guest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/student?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: true